# Form implementation generated from reading ui file 'scenes\challengepreview\ChallengePreview.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ChallengePreview(object):
    def setupUi(self, ChallengePreview):
        ChallengePreview.setObjectName("ChallengePreview")
        ChallengePreview.resize(294, 273)
        self.verticalLayout = QtWidgets.QVBoxLayout(ChallengePreview)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_challenge_list = QtWidgets.QLabel(ChallengePreview)
        self.lbl_challenge_list.setObjectName("lbl_challenge_list")
        self.verticalLayout.addWidget(self.lbl_challenge_list)
        self.tbl_challenges = QtWidgets.QTableView(ChallengePreview)
        self.tbl_challenges.setObjectName("tbl_challenges")
        self.verticalLayout.addWidget(self.tbl_challenges)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_start = QtWidgets.QPushButton(ChallengePreview)
        self.btn_start.setEnabled(False)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout.addWidget(self.btn_start)
        self.btn_pause = QtWidgets.QPushButton(ChallengePreview)
        self.btn_pause.setEnabled(False)
        self.btn_pause.setObjectName("btn_pause")
        self.horizontalLayout.addWidget(self.btn_pause)
        self.btn_stop = QtWidgets.QPushButton(ChallengePreview)
        self.btn_stop.setEnabled(False)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout.addWidget(self.btn_stop)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ChallengePreview)
        QtCore.QMetaObject.connectSlotsByName(ChallengePreview)

    def retranslateUi(self, ChallengePreview):
        _translate = QtCore.QCoreApplication.translate
        ChallengePreview.setWindowTitle(_translate("ChallengePreview", "Демонстрация"))
        self.lbl_challenge_list.setText(_translate("ChallengePreview", "Список испытаний:"))
        self.btn_start.setText(_translate("ChallengePreview", "Старт"))
        self.btn_pause.setText(_translate("ChallengePreview", "Пауза"))
        self.btn_stop.setText(_translate("ChallengePreview", "Стоп"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChallengePreview = QtWidgets.QDialog()
    ui = Ui_ChallengePreview()
    ui.setupUi(ChallengePreview)
    ChallengePreview.show()
    sys.exit(app.exec())
