# Form implementation generated from reading ui file 'scenes\activechallenge\ActiveChallenge.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ActiveChallenge(object):
    def setupUi(self, ActiveChallenge):
        ActiveChallenge.setObjectName("ActiveChallenge")
        ActiveChallenge.resize(231, 213)
        self.groupBox = QtWidgets.QGroupBox(ActiveChallenge)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 211, 81))
        self.groupBox.setObjectName("groupBox")
        self.cb_final = QtWidgets.QCheckBox(self.groupBox)
        self.cb_final.setGeometry(QtCore.QRect(10, 20, 151, 20))
        self.cb_final.setObjectName("cb_final")
        self.cb_timeout = QtWidgets.QCheckBox(self.groupBox)
        self.cb_timeout.setGeometry(QtCore.QRect(10, 50, 171, 20))
        self.cb_timeout.setObjectName("cb_timeout")
        self.btn_start = QtWidgets.QPushButton(ActiveChallenge)
        self.btn_start.setGeometry(QtCore.QRect(10, 100, 211, 24))
        self.btn_start.setObjectName("btn_start")
        self.btn_success = QtWidgets.QPushButton(ActiveChallenge)
        self.btn_success.setEnabled(False)
        self.btn_success.setGeometry(QtCore.QRect(10, 180, 101, 24))
        self.btn_success.setObjectName("btn_success")
        self.btn_fail = QtWidgets.QPushButton(ActiveChallenge)
        self.btn_fail.setEnabled(False)
        self.btn_fail.setGeometry(QtCore.QRect(120, 180, 101, 24))
        self.btn_fail.setObjectName("btn_fail")
        self.btn_stop = QtWidgets.QPushButton(ActiveChallenge)
        self.btn_stop.setEnabled(False)
        self.btn_stop.setGeometry(QtCore.QRect(10, 130, 211, 24))
        self.btn_stop.setObjectName("btn_stop")

        self.retranslateUi(ActiveChallenge)
        QtCore.QMetaObject.connectSlotsByName(ActiveChallenge)

    def retranslateUi(self, ActiveChallenge):
        _translate = QtCore.QCoreApplication.translate
        ActiveChallenge.setWindowTitle(_translate("ActiveChallenge", "Испытание"))
        self.groupBox.setTitle(_translate("ActiveChallenge", "Настройки"))
        self.cb_final.setText(_translate("ActiveChallenge", "Финал"))
        self.cb_timeout.setText(_translate("ActiveChallenge", "Авто провал при таймауте"))
        self.btn_start.setText(_translate("ActiveChallenge", "Начать испытание"))
        self.btn_success.setText(_translate("ActiveChallenge", "Успех"))
        self.btn_fail.setText(_translate("ActiveChallenge", "Провал"))
        self.btn_stop.setText(_translate("ActiveChallenge", "Прервать испытание"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ActiveChallenge = QtWidgets.QDialog()
    ui = Ui_ActiveChallenge()
    ui.setupUi(ActiveChallenge)
    ActiveChallenge.show()
    sys.exit(app.exec())
